import sys
T = '\t'
TT = '\t\t'
Q = '"'
NL = '\n'

lines = [
'extends Control',
'class_name TacticalUI',
'',
'signal combat_finished(outcome: String)',
'',
'var combat_engine: CombatEngine',
'var game_state: GameState',
'var crew: Array = []',
'var _crew_panel_vbox: VBoxContainer',
'var _crew_rows: Array = []',
'var _player_hull_bar: ProgressBar',
'var _player_hull_label: Label',
'var _enemy_hull_bar: ProgressBar',
'var _enemy_hull_label: Label',
'var _enemy_name_label: Label',
'var _enemy_shield_label: Label',
'var _turn_log_vbox: VBoxContainer',
'var _turn_log_scroll: ScrollContainer',
'var _action_attack: Button',
'var _action_repair: Button',
'var _action_evade: Button',
'var _result_label: Label',
'var _continue_btn: Button',
'',
'func _ready() -> void:',
T+'_build_layout()',
'',
'func _build_layout() -> void:',
T+'set_anchors_preset(Control.PRESET_FULL_RECT)',
T+'var bg = ColorRect.new()',
T+'bg.color = Color(0.05, 0.04, 0.10)',
T+'bg.set_anchors_preset(Control.PRESET_FULL_RECT)',
T+'add_child(bg)',
T+'var root_hbox = HBoxContainer.new()',
T+'root_hbox.set_anchors_preset(Control.PRESET_FULL_RECT)',
T+'root_hbox.add_theme_constant_override("separation", 0)',
T+'add_child(root_hbox)',
T+'root_hbox.add_child(_build_crew_panel())',
T+'root_hbox.add_child(_build_center_panel())',
T+'root_hbox.add_child(_build_enemy_panel())',
'',
'func _build_crew_panel() -> PanelContainer:',
T+'var panel = PanelContainer.new()',
T+'panel.custom_minimum_size = Vector2(300, 0)',
T+'var vbox = VBoxContainer.new()',
T+'vbox.add_theme_constant_override("separation", 6)',
T+'panel.add_child(vbox)',
T+'var title = Label.new()',
T+'title.text = "CREW STATUS"',
T+'title.add_theme_font_size_override("font_size", 15)',
T+'vbox.add_child(title)',
T+'var hull_hbox = HBoxContainer.new()',
T+'var hl = Label.new(); hl.text = "Ship Hull:"; hl.custom_minimum_size = Vector2(70, 0)',
T+'hull_hbox.add_child(hl)',
T+'_player_hull_bar = ProgressBar.new()',
T+'_player_hull_bar.min_value = 0; _player_hull_bar.max_value = 100; _player_hull_bar.value = 100',
T+'_player_hull_bar.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
T+'hull_hbox.add_child(_player_hull_bar)',
T+'_player_hull_label = Label.new(); _player_hull_label.text = "100"; _player_hull_label.custom_minimum_size = Vector2(34, 0)',
T+'hull_hbox.add_child(_player_hull_label)',
T+'vbox.add_child(hull_hbox)',
T+'vbox.add_child(HSeparator.new())',
T+'var crew_hdr = Label.new(); crew_hdr.text = "CREW"; crew_hdr.add_theme_font_size_override("font_size", 12)',
T+'vbox.add_child(crew_hdr)',
T+'_crew_panel_vbox = VBoxContainer.new()',
T+'_crew_panel_vbox.add_theme_constant_override("separation", 4)',
T+'vbox.add_child(_crew_panel_vbox)',
T+'return panel',
'',
'func _build_crew_row(member) -> Dictionary:',
T+'var row_root = VBoxContainer.new()',
T+'row_root.add_theme_constant_override("separation", 2)',
T+'var name_hbox = HBoxContainer.new()',
T+'var name_lbl = Label.new()',
T+'name_lbl.text = "%s (%s)" % [member.name, member.role]',
T+'name_lbl.add_theme_font_size_override("font_size", 11)',
T+'name_lbl.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
T+'name_hbox.add_child(name_lbl)',
T+'var badge = Label.new(); badge.text = "OK"; badge.add_theme_font_size_override("font_size", 10)',
T+'badge.custom_minimum_size = Vector2(64, 0)',
T+'name_hbox.add_child(badge)',
T+'row_root.add_child(name_hbox)',
T+'var hp_hbox = HBoxContainer.new()',
T+'var hp_lbl = Label.new(); hp_lbl.text = "HP"; hp_lbl.custom_minimum_size = Vector2(24, 0); hp_lbl.add_theme_font_size_override("font_size", 10); hp_hbox.add_child(hp_lbl)',
T+'var hp_bar = ProgressBar.new(); hp_bar.min_value = 0; hp_bar.max_value = 100; hp_bar.value = member.health; hp_bar.size_flags_horizontal = Control.SIZE_EXPAND_FILL; hp_hbox.add_child(hp_bar)',
T+'row_root.add_child(hp_hbox)',
T+'var mo_hbox = HBoxContainer.new()',
T+'var mo_lbl = Label.new(); mo_lbl.text = "MO"; mo_lbl.custom_minimum_size = Vector2(24, 0); mo_lbl.add_theme_font_size_override("font_size", 10); mo_hbox.add_child(mo_lbl)',
T+'var mo_bar = ProgressBar.new(); mo_bar.min_value = 0; mo_bar.max_value = 100; mo_bar.value = member.morale; mo_bar.size_flags_horizontal = Control.SIZE_EXPAND_FILL; mo_hbox.add_child(mo_bar)',
T+'row_root.add_child(mo_hbox)',
T+'var st_hbox = HBoxContainer.new()',
T+'var st_lbl = Label.new(); st_lbl.text = "ST"; st_lbl.custom_minimum_size = Vector2(24, 0); st_lbl.add_theme_font_size_override("font_size", 10); st_hbox.add_child(st_lbl)',
T+'var st_bar = ProgressBar.new(); st_bar.min_value = 0; st_bar.max_value = 100; st_bar.value = member.stress; st_bar.size_flags_horizontal = Control.SIZE_EXPAND_FILL; st_hbox.add_child(st_bar)',
T+'row_root.add_child(st_hbox)',
T+'var extras = Label.new(); extras.add_theme_font_size_override("font_size", 9); extras.text = _build_extras_text(member)',
T+'row_root.add_child(extras)',
T+'_crew_panel_vbox.add_child(row_root)',
T+'if crew.find(member) < crew.size() - 1:',
TT+'_crew_panel_vbox.add_child(HSeparator.new())',
T+'return {"root": row_root, "badge": badge, "hp_bar": hp_bar, "mo_bar": mo_bar, "st_bar": st_bar, "extras": extras, "member": member}',
'',
'func _build_extras_text(member) -> String:',
T+'var parts: Array = []',
T+'if member.has_method("get_primary_skill"):',
TT+'var sk = member.get_primary_skill()',
TT+'if sk != "":',
TT+T+'var lvl_names = ["Novice", "Proficient", "Expert"]',
TT+T+'parts.append("%s: %s" % [sk.capitalize(), lvl_names[member.skill_level.get(sk, 0)]])',
T+'if not member.phobias.is_empty():',
TT+'parts.append("! " + ", ".join(member.phobias))',
T+'if not member.ambition_id.is_empty():',
TT+'if member.ambition_complete: parts.append("* Goal done")',
TT+'else: parts.append("Goal %d%%" % member.ambition_progress)',
T+'return " | ".join(parts)',
'',
'func _get_status_badge(member) -> String:',
T+'if member.health <= 0:  return "DEAD"',
T+'if member.stress > 75:  return "PANICKED"',
T+'if member.morale <= 20: return "DESPAIR"',
T+'if member.health < 30:  return "CRITICAL"',
T+'if member.morale > 80 and member.stress < 20: return "EXCELLENT"',
T+'return "OK"',
'',
'func _rebuild_crew_rows() -> void:',
T+'for child in _crew_panel_vbox.get_children():',
TT+'child.queue_free()',
T+'_crew_rows.clear()',
T+'for member in crew:',
TT+'_crew_rows.append(_build_crew_row(member))',
'',
'func _build_center_panel() -> VBoxContainer:',
T+'var outer = VBoxContainer.new()',
T+'outer.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
T+'var margin = MarginContainer.new()',
T+'margin.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
T+'margin.size_flags_vertical = Control.SIZE_EXPAND_FILL',
T+'for side in ["left", "right", "top", "bottom"]:',
TT+'margin.add_theme_constant_override("margin_" + side, 14)',
T+'outer.add_child(margin)',
T+'var inner = VBoxContainer.new()',
T+'inner.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
T+'inner.size_flags_vertical = Control.SIZE_EXPAND_FILL',
T+'inner.add_theme_constant_override("separation", 10)',
T+'margin.add_child(inner)',
T+'var title = Label.new(); title.text = "-- COMBAT --"; title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER; title.add_theme_font_size_override("font_size", 22)',
T+'inner.add_child(title)',
T+'_turn_log_scroll = ScrollContainer.new()',
T+'_turn_log_scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL',
T+'_turn_log_scroll.custom_minimum_size = Vector2(0, 300)',
T+'inner.add_child(_turn_log_scroll)',
T+'_turn_log_vbox = VBoxContainer.new()',
T+'_turn_log_vbox.add_theme_constant_override("separation", 3)',
T+'_turn_log_vbox.size_flags_horizontal = Control.SIZE_EXPAND_FILL',
T+'_turn_log_scroll.add_child(_turn_log_vbox)',
T+'_result_label = Label.new(); _result_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER; _result_label.add_theme_font_size_override("font_size", 26); _result_label.visible = false',
T+'inner.add_child(_result_label)',
T+'var action_lbl = Label.new(); action_lbl.text = "Choose your action:"; action_lbl.add_theme_font_size_override("font_size", 13)',
T+'inner.add_child(action_lbl)',
T+'var btn_hbox = HBoxContainer.new(); btn_hbox.add_theme_constant_override("separation", 12)',
T+'inner.add_child(btn_hbox)',
T+'_action_attack = Button.new(); _action_attack.text = "ATTACK\\nDeal damage"; _action_attack.custom_minimum_size = Vector2(150, 60); _action_attack.pressed.connect(_on_attack_pressed)',
T+'btn_hbox.add_child(_action_attack)',
T+'_action_repair = Button.new(); _action_repair.text = "REPAIR\\nRestore hull"; _action_repair.custom_minimum_size = Vector2(150, 60); _action_repair.pressed.connect(_on_repair_pressed)',
T+'btn_hbox.add_child(_action_repair)',
T+'_action_evade = Button.new(); _action_evade.text = "EVADE\\nReduce next hit"; _action_evade.custom_minimum_size = Vector2(150, 60); _action_evade.pressed.connect(_on_evade_pressed)',
T+'btn_hbox.add_child(_action_evade)',
T+'_continue_btn = Button.new(); _continue_btn.text = "CONTINUE"; _continue_btn.custom_minimum_size = Vector2(200, 50); _continue_btn.visible = false; _continue_btn.pressed.connect(_on_continue_pressed)',
T+'inner.add_child(_continue_btn)',
T+'return outer',
'',
'func _build_enemy_panel() -> PanelContainer:',
T+'var panel = PanelContainer.new()',
T+'panel.custom_minimum_size = Vector2(220, 0)',
T+'var vbox = VBoxContainer.new(); vbox.add_theme_constant_override("separation", 8); panel.add_child(vbox)',
T+'var title = Label.new(); title.text = "ENEMY SHIP"; title.add_theme_font_size_override("font_size", 15); vbox.add_child(title)',
T+'_enemy_name_label = Label.new(); _enemy_name_label.text = "Unknown"; _enemy_name_label.add_theme_font_size_override("font_size", 12); vbox.add_child(_enemy_name_label)',
T+'var hull_hbox = HBoxContainer.new()',
T+'var elbl = Label.new(); elbl.text = "Hull:"; elbl.custom_minimum_size = Vector2(40, 0); hull_hbox.add_child(elbl)',
T+'_enemy_hull_bar = ProgressBar.new(); _enemy_hull_bar.min_value = 0; _enemy_hull_bar.max_value = 100; _enemy_hull_bar.value = 100; _enemy_hull_bar.size_flags_horizontal = Control.SIZE_EXPAND_FILL; hull_hbox.add_child(_enemy_hull_bar)',
T+'_enemy_hull_label = Label.new(); _enemy_hull_label.text = "100"; _enemy_hull_label.custom_minimum_size = Vector2(34, 0); hull_hbox.add_child(_enemy_hull_label)',
T+'vbox.add_child(hull_hbox)',
T+'_enemy_shield_label = Label.new(); _enemy_shield_label.text = ""; _enemy_shield_label.add_theme_font_size_override("font_size", 11); vbox.add_child(_enemy_shield_label)',
T+'return panel',
'',
'func bind_combat(p_combat_engine: CombatEngine, p_game_state: GameState, p_crew: Array) -> void:',
T+'combat_engine = p_combat_engine',
T+'game_state = p_game_state',
T+'crew = p_crew',
T+'_rebuild_crew_rows()',
T+'_update_enemy_info()',
T+'_log_line("=== COMBAT BEGIN ===")',
T+'_log_line("Your hull: %d  |  Enemy hull: %d" % [combat_engine.combat_state.get("player_hull", 100), combat_engine.combat_state.get("enemy_hull", 30)])',
'',
'func update_display() -> void:',
T+'if not combat_engine: return',
T+'var state = combat_engine.combat_state',
T+'var ph = state.get("player_hull", 100)',
T+'_player_hull_bar.value = ph; _player_hull_label.text = str(ph)',
T+'var eh = state.get("enemy_hull", 30)',
T+'var eh_max = combat_engine.enemy_template.get("hull", 30)',
T+'_enemy_hull_bar.max_value = eh_max; _enemy_hull_bar.value = eh; _enemy_hull_label.text = "%d/%d" % [eh, eh_max]',
T+'_enemy_shield_label.text = "[ SHIELDED ]" if state.get("enemy_shielded", false) else ""',
T+'for row in _crew_rows:',
TT+'var m = row["member"]',
TT+'row["hp_bar"].value = m.health; row["mo_bar"].value = m.morale; row["st_bar"].value = m.stress',
TT+'row["badge"].text = _get_status_badge(m); row["extras"].text = _build_extras_text(m)',
'',
'func _on_attack_pressed() -> void: _do_turn("attack_weapons")',
'func _on_repair_pressed() -> void: _do_turn("repair")',
'func _on_evade_pressed() -> void:  _do_turn("evade")',
'',
'func _do_turn(player_action: String) -> void:',
T+'if not combat_engine or combat_engine.is_combat_over(): return',
T+'_set_actions_enabled(false)',
T+'var result = combat_engine.advance_turn(player_action)',
T+'var player_dmg = result.get("last_player_damage", 0)',
T+'var player_heal = result.get("last_player_heal", 0)',
T+'var enemy_dmg = result.get("last_enemy_damage", 0)',
T+'var enemy_act = result.get("last_enemy_action", "?")',
T+'var p_str := ""',
T+'if player_action == "attack_weapons": p_str = "You attacked for %d dmg" % player_dmg',
T+'elif player_action == "repair": p_str = "You repaired %d hull" % player_heal',
T+'elif player_action == "evade": p_str = "You evaded (next hit reduced)"',
T+'var e_str = "%s: %d dmg to you" % [enemy_act, enemy_dmg] if enemy_dmg > 0 else enemy_act',
T+'_log_line("Turn %d: %s | Enemy: %s" % [result.get("tick", 0), p_str, e_str])',
T+'_log_line("  Hull: yours %d  |  enemy %d" % [result.get("player_hull", 0), result.get("enemy_hull", 0)])',
T+'update_display()',
T+'if combat_engine.is_combat_over(): _show_result(result.get("outcome", "ongoing"))',
T+'else: _set_actions_enabled(true)',
'',
'func _update_enemy_info() -> void:',
T+'if not combat_engine or combat_engine.enemy_template.is_empty(): return',
T+'var faction = combat_engine.enemy_template.get("faction", "unknown")',
T+'var eid = combat_engine.enemy_template.get("id", "?")',
T+'_enemy_name_label.text = "%s\n[%s]" % [eid.replace("_", " ").capitalize(), faction]',
T+'var eh = combat_engine.enemy_template.get("hull", 30)',
T+'_enemy_hull_bar.max_value = eh; _enemy_hull_bar.value = eh; _enemy_hull_label.text = "%d/%d" % [eh, eh]',
'',
'func _log_line(text: String) -> void:',
T+'var lbl = Label.new(); lbl.text = text; lbl.add_theme_font_size_override("font_size", 11); lbl.autowrap_mode = TextServer.AUTOWRAP_WORD',
T+'_turn_log_vbox.add_child(lbl)',
T+'get_tree().create_timer(0.05).timeout.connect(func():',
TT+'if is_instance_valid(_turn_log_scroll): _turn_log_scroll.scroll_vertical = 999999)',
'',
'func _show_result(outcome: String) -> void:',
T+'_set_actions_enabled(false)',
T+'match outcome:',
TT+'"victory": _result_label.text = "VICTORY"; _result_label.add_theme_color_override("font_color", Color.GOLD)',
TT+'"defeat":  _result_label.text = "DEFEAT";  _result_label.add_theme_color_override("font_color", Color.RED)',
TT+'_:         _result_label.text = outcome.to_upper()',
T+'_result_label.visible = true',
T+'_continue_btn.visible = true',
T+'_log_line("=== COMBAT OVER: %s ===" % outcome.to_upper())',
'',
'func _set_actions_enabled(enabled: bool) -> void:',
T+'_action_attack.disabled = not enabled',
T+'_action_repair.disabled = not enabled',
T+'_action_evade.disabled = not enabled',
'',
'func _on_continue_pressed() -> void:',
T+'emit_signal("combat_finished", combat_engine.combat_state.get("outcome", "ongoing"))',
]

with open('game/scripts/ui/tactical_ui.gd', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('written', len(lines), 'lines')
